import React from 'react';
import {BadgeCheck, LockKeyhole, ShieldCheck, Sparkles} from 'lucide-react';
import {AbsoluteFill, interpolate, useCurrentFrame} from 'remotion';
import {Brand, CaptionRail, Cursor, Eyebrow} from '../components';
import {fonts, palette, reveal, softScale} from '../theme';

export const LoginScene: React.FC = () => {
  const frame = useCurrentFrame();
  const authenticated = frame > 116;
  const swap = interpolate(frame, [112, 130], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
  return <AbsoluteFill style={{background: palette.deep, color: palette.paper, overflow: 'hidden'}}>
    <div style={{position: 'absolute', width: 620, height: 620, border: '1px solid rgba(200,255,125,.18)', borderRadius: 700, right: -120, top: 80}} /><div style={{position: 'absolute', width: 370, height: 370, border: '1px solid rgba(200,255,125,.12)', borderRadius: 700, right: 5, top: 205}} />
    <header style={{position: 'absolute', top: 54, left: 74, right: 74, display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}><Brand light /></header>
    <div style={{position: 'absolute', left: 120, top: 270, width: 650, ...reveal(frame, 6)}}><Eyebrow light>PRIVATE GUEST ACCESS</Eyebrow><h2 style={{fontFamily: fonts.serif, fontSize: 84, fontWeight: 420, lineHeight: .94, letterSpacing: '-.05em', margin: '34px 0 26px'}}>A secure space<br /><em>for every stay.</em></h2><p style={{fontSize: 20, lineHeight: 1.55, color: 'rgba(251,250,244,.68)', width: 540}}>Supabase Auth restores the guest session, while row-level security keeps reservations and saved hotels tied to their owner.</p><div style={{display: 'flex', gap: 16, marginTop: 38}}><div style={{display: 'flex', gap: 10, alignItems: 'center', fontSize: 14}}><ShieldCheck color={palette.lime} />Authenticated access</div><div style={{display: 'flex', gap: 10, alignItems: 'center', fontSize: 14}}><LockKeyhole color={palette.lime} />Owner-only records</div></div></div>
    <div style={{position: 'absolute', right: 220, top: 190, width: 560, minHeight: 690, padding: 54, border: '1px solid rgba(255,255,255,.16)', background: 'rgba(3,41,33,.82)', boxShadow: '0 50px 100px rgba(0,0,0,.25)', ...softScale(frame, 18)}}>
      {!authenticated ? <div style={{opacity: 1 - swap}}><span style={{width: 48, height: 48, borderRadius: 50, display: 'grid', placeItems: 'center', border: `1px solid ${palette.lime}`, color: palette.lime}}><Sparkles size={20} /></span><small style={{display: 'block', color: palette.lime, fontWeight: 700, letterSpacing: '.15em', marginTop: 38}}>PRIVATE GUEST ACCESS</small><h3 style={{fontFamily: fonts.serif, fontSize: 54, fontWeight: 450, lineHeight: 1, margin: '24px 0 42px'}}>Your stay starts<br /><em>with a conversation.</em></h3><label style={{display: 'block', fontSize: 10, letterSpacing: '.14em', color: palette.moss}}>ACCOUNT<div style={{border: '1px solid rgba(255,255,255,.25)', marginTop: 10, padding: '20px 18px', fontSize: 16, color: palette.paper}}>IO-DEMO</div></label><label style={{display: 'block', fontSize: 10, letterSpacing: '.14em', color: palette.moss, marginTop: 20}}>PASSWORD<div style={{border: '1px solid rgba(255,255,255,.25)', marginTop: 10, padding: '20px 18px', fontSize: 16, letterSpacing: '.2em'}}>••••••••</div></label><button style={{width: '100%', border: 0, marginTop: 28, padding: 20, background: palette.lime, color: palette.ink, textAlign: 'left', fontWeight: 800}}>ENTER STAYAI <LockKeyhole size={18} style={{float: 'right'}} /></button><Cursor x={455} y={555} clickAt={88} /></div> : <div style={{opacity: swap, textAlign: 'center', paddingTop: 130}}><BadgeCheck size={72} color={palette.lime} strokeWidth={1.2} /><small style={{display: 'block', color: palette.lime, letterSpacing: '.16em', marginTop: 26}}>SESSION RESTORED</small><h3 style={{fontFamily: fonts.serif, fontSize: 62, fontWeight: 430, margin: '24px 0 16px'}}>Welcome back.</h3><p style={{color: 'rgba(255,255,255,.62)', fontSize: 18}}>Your private StayAI workspace is ready.</p></div>}
    </div>
    <CaptionRail step="YOU" title="Sign in once to open your private workspace." detail="STAYAI — Supabase restores the session and row-level security keeps every record owner-scoped." light delay={26} />
  </AbsoluteFill>;
};
