import React from 'react';
import {ArrowRight, CalendarDays, Check, MapPin, RefreshCw, RotateCcw, Sparkles, X} from 'lucide-react';
import {AbsoluteFill, Img, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {Browser, CaptionRail, Cursor} from '../components';
import {fonts, palette, reveal} from '../theme';

export const MyStayScene: React.FC = () => {
  const frame = useCurrentFrame();
  const cancelled = frame > 126;
  const restored = frame > 202;
  const statusProgress = interpolate(frame, [120, 145, 198, 220], [0, 1, 1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
  return <AbsoluteFill style={{background: '#dce5de', padding: 58}}>
    <Browser style={{height: '100%'}}>
      <div style={{height: 894, background: palette.cream, padding: '48px 60px', position: 'relative'}}>
        <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', ...reveal(frame, 4)}}><div><small style={{color: palette.forest, fontWeight: 800, letterSpacing: '.16em'}}>PERSISTENT GUEST RECORDS</small><h2 style={{fontFamily: fonts.serif, fontSize: 54, fontWeight: 440, margin: '13px 0 0'}}>My stay, clearly arranged.</h2></div><button style={{border: 0, background: palette.forest, color: palette.paper, padding: '16px 20px'}}><Sparkles size={17} style={{verticalAlign: 'middle', marginRight: 8}} />Ask StayAI <ArrowRight size={16} style={{verticalAlign: 'middle'}} /></button></div>
        <nav style={{display: 'flex', gap: 36, borderBottom: `1px solid ${palette.line}`, marginTop: 34}}>{[['Upcoming', restored || !cancelled ? '1' : '0'], ['Cancelled', cancelled && !restored ? '1' : '0'], ['Saved', '2']].map(([label, count], i) => <span key={label} style={{padding: '16px 0', borderBottom: i === (cancelled && !restored ? 1 : 0) ? `2px solid ${palette.forest}` : '2px solid transparent', fontWeight: 700}}>{label} <small style={{marginLeft: 6, background: '#e4eae3', padding: '4px 7px', borderRadius: 20}}>{count}</small></span>)}<span style={{marginLeft: 'auto', padding: '16px 0', color: palette.moss}}><RefreshCw size={15} style={{verticalAlign: 'middle', marginRight: 7}} />Refresh</span></nav>
        <article style={{marginTop: 30, display: 'grid', gridTemplateColumns: '270px 1fr 410px 200px', alignItems: 'stretch', minHeight: 330, background: palette.paper, border: `1px solid ${palette.line}`, boxShadow: '0 22px 60px rgba(8,47,39,.1)', ...reveal(frame, 18)}}><div style={{position: 'relative'}}><Img src={staticFile('assets/hotel-lisbon-1.jpg')} style={{width: '100%', height: '100%', objectFit: 'cover'}} /></div><div style={{padding: '46px 36px'}}><small style={{color: cancelled && !restored ? palette.rust : palette.forest, fontWeight: 800, letterSpacing: '.13em'}}>{cancelled && !restored ? 'CANCELLED DEMO STAY' : 'UPCOMING DEMO STAY'}</small><h3 style={{fontFamily: fonts.serif, fontSize: 38, fontWeight: 450, margin: '16px 0 12px'}}>Bairro Alto Hotel</h3><p style={{display: 'flex', gap: 8, color: '#61746e'}}><MapPin size={16} />Lisbon · Chiado</p><span style={{display: 'inline-flex', alignItems: 'center', gap: 8, marginTop: 28, border: `1px solid ${palette.line}`, padding: '10px 13px', fontSize: 12}}><Check size={15} />IO—7K4M2P</span></div><div style={{padding: '46px 30px', borderLeft: `1px solid ${palette.line}`, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18}}><div><small>DATES</small><strong style={{display: 'block', marginTop: 9}}>18—22 Sep</strong></div><div><small>PARTY</small><strong style={{display: 'block', marginTop: 9}}>2 guests</strong></div><div><small>QUOTED TOTAL</small><strong style={{display: 'block', marginTop: 9}}>€1,376</strong></div><div><small>SOURCE</small><strong style={{display: 'block', marginTop: 9}}>Xotelo</strong></div></div><div style={{padding: '46px 28px', borderLeft: `1px solid ${palette.line}`, display: 'flex', flexDirection: 'column', justifyContent: 'space-between'}}><span style={{display: 'flex', alignItems: 'center', gap: 8, color: cancelled && !restored ? palette.rust : palette.forest}}><i style={{width: 9, height: 9, borderRadius: 10, background: 'currentColor'}} />{cancelled && !restored ? 'Cancelled' : 'Confirmed'}</span><button style={{border: 0, padding: '14px', background: cancelled && !restored ? palette.lime : '#eee9df', color: palette.ink}}>{cancelled && !restored ? <><RotateCcw size={15} style={{verticalAlign: 'middle'}} /> Reactivate</> : <>Open details <ArrowRight size={15} style={{verticalAlign: 'middle'}} /></>}</button></div></article>
        <div style={{marginTop: 24, display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 14}}>{[['Upcoming', 'Review every active demo stay'], ['Cancelled', 'Records remain visible'], ['Saved', 'Shortlist properties for later']].map(([title, detail], i) => <div key={title} style={{padding: 20, border: `1px solid ${palette.line}`, background: 'rgba(251,250,244,.65)', ...reveal(frame, 42 + i * 8)}}><small style={{letterSpacing: '.13em', color: palette.forest}}>0{i + 1}</small><strong style={{fontFamily: fonts.serif, fontSize: 23, display: 'block', marginTop: 9}}>{title}</strong><span style={{fontSize: 13, color: '#657871'}}>{detail}</span></div>)}</div>
        <div style={{position: 'absolute', left: 760, top: 340, opacity: statusProgress, background: palette.deep, color: palette.paper, padding: '18px 24px', boxShadow: '0 18px 50px rgba(0,0,0,.22)', zIndex: 20}}><small style={{color: palette.lime, letterSpacing: '.13em'}}>SUPABASE UPDATED</small><strong style={{display: 'block', marginTop: 5}}>{restored ? 'Reservation reactivated' : 'Reservation cancelled'}</strong></div>
      </div>
    </Browser>
    {frame > 84 && frame < 145 && <Cursor x={1650} y={584} clickAt={104} />}{frame > 168 && frame < 226 && <Cursor x={1650} y={584} clickAt={188} />}
    <CaptionRail step="YOU" title="Return to My Stay to inspect, cancel or reactivate." detail="RESULT — Upcoming, cancelled and saved records remain organized and synchronized with Supabase." delay={22} />
  </AbsoluteFill>;
};
